<?php

    namespace App\Socialite;

    use GuzzleHttp\Exception\GuzzleException;
    use JsonException;
    use Laravel\Socialite\Two\AbstractProvider;
    use Laravel\Socialite\Two\User;

    /**
     * Custom Socialite provider for authenticating against a Forge OAuth 2.0 server.
     *
     * This provider is used by Laravel Socialite to:
     * - Build the Forge authorization URL
     * - Exchange an authorization code for an access token
     * - Fetch the authenticated Forge user profile
     * - Normalize the profile into a Socialite `User` object
     *
     * Forge instance requirements:
     * - Laravel Passport installed/enabled
     * - OAuth client created for this Codex installation
     *
     * Expected environment/config values:
     * - FORGE_ENABLED=true
     * - FORGE_URL=https://forge.example.com
     * - FORGE_CLIENT_ID=<passport client uuid>
     * - FORGE_CLIENT_SECRET=<passport client secret>
     * - FORGE_REDIRECT_URI=https://codex.example.com/auth/forge/callback
     */
    class ForgeProvider extends AbstractProvider
    {
        /**
         * OAuth scopes requested during authorization.
         *
         * @var array<int, string>
         */
        protected $scopes = ['profile', 'email'];

        /**
         * Delimiter used when serializing scope values in the auth URL.
         *
         * @var string
         */
        protected $scopeSeparator = ' ';

        /**
         * Build the full OAuth authorization endpoint URL.
         *
         * @param string $state CSRF state token generated by Socialite.
         * @return string Fully qualified authorization URL.
         */
        protected function getAuthUrl($state): string
        {
            return $this->buildAuthUrlFromBase(
                rtrim(config('codex.forge.url'), '/') . '/oauth/authorize',
                $state
            );
        }

        /**
         * Get the OAuth token endpoint URL used to exchange the auth code.
         *
         * @return string Fully qualified token URL.
         */
        protected function getTokenUrl(): string
        {
            return rtrim(config('codex.forge.url'), '/') . '/oauth/token';
        }

        /**
         * Fetch the current authenticated user profile from Forge using an access token.
         *
         * The Forge API typically returns either:
         * - { "data": { ...user fields... } }
         * - { ...user fields... }
         *
         * This method supports both shapes by returning `$body['data']` when present,
         * otherwise returning the full response body.
         *
         * @param string $token OAuth access token.
         * @return array<string, mixed> Raw user payload from Forge.
         * @throws JsonException When response JSON cannot be decoded.
         * @throws GuzzleException When the HTTP request fails.
         */
        protected function getUserByToken($token): array
        {
            $response = $this->getHttpClient()->get(
                rtrim(config('codex.forge.url'), '/') . '/api/v1/me',
                [
                    'headers' => [
                        'Authorization' => 'Bearer ' . $token,
                        'Accept'        => 'application/json',
                    ],
                ]
            );

            $body = json_decode((string) $response->getBody(), true, 512, JSON_THROW_ON_ERROR);

            return $body['data'] ?? $body;
        }

        /**
         * Map Forge user payload fields to Socialite's normalized `User` object.
         *
         * @param array<string, mixed> $user Raw Forge user payload.
         * @return User Normalized Socialite user instance.
         */
        protected function mapUserToObject($user): User
        {
            return (new User)->setRaw($user)->map([
                'id'       => $user['id'] ?? null,
                'name'     => $user['name'] ?? null,
                'email'    => $user['email'] ?? null,
                'avatar'   => $user['avatar_url'] ?? null,
                'nickname' => $user['name'] ?? null,
            ]);
        }
    }
